# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 */6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Display blog posts on README.md
      - name: zenn
        id: zenn
        uses: sarisia/actions-readme-feed@v1.3.1
        with:
          url: 'https://zenn.dev/littleforest/feed'
          file: 'README.md'
          start_flag: "<!-- zenn start -->"
          end_flag: "<!-- zenn end -->"
      - name: qiita
        id: qiita
        uses: sarisia/actions-readme-feed@v1.3.1
        with:
          url: 'https://qiita.com/Littleforest/feed'
          file: 'README.md'
          start_flag: "<!-- qiita start -->"
          end_flag: "<!-- qiita end -->"
      
      # commit changes if something has changed
      - if: steps.zenn.outputs.changed == true || steps.qiita.outputs.changed == true
        uses: sarisia/actions-commit@master
